-- The LoanMate schema now lives in supabase/migrations/20261004000000_loanmate_schema.sql.
-- Run that file in the Supabase SQL editor (or `supabase db push`). It is idempotent and
-- upgrades databases created from the previous version of this file.
